// packages/react/src/Tinyflow.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import {
    Tinyflow as TinyflowNative,
    type TinyflowOptions as TinyflowNativeOptions
} from '@tinyflow-ai/ui';
import '@tinyflow-ai/ui/dist/index.css';

export type TinyflowOptions = {
    style?: React.CSSProperties;
    className?: string;
} & Omit<TinyflowNativeOptions, 'element'>;

export interface TinyflowHandle {
    getData: () => any;
}

const Tinyflow = forwardRef<TinyflowHandle, TinyflowOptions>((options, ref) => {
    const divRef = useRef<HTMLDivElement | null>(null);
    const tinyflowInstance = useRef<TinyflowNative | null>(null);

    useImperativeHandle(ref, () => ({
        getData: () => {
            if (tinyflowInstance.current) {
                return tinyflowInstance.current.getData();
            }
            console.warn('Tinyflow instance is not initialized');
            return null;
        },
        getInstance: () => {
            if (tinyflowInstance.current) {
                return tinyflowInstance.current;
            }
            console.warn('Tinyflow instance is not initialized');
            return null;
        }
    }));

    const { data, style, className } = options;

    useEffect(() => {
        if (divRef.current) {
            const tinyflow = new TinyflowNative({
                ...options,
                element: divRef.current
                // data: data
            });

            tinyflowInstance.current = tinyflow;

            return () => {
                tinyflow.destroy();
                tinyflowInstance.current = null;
            };
        }
    }, [data]);

    return <div ref={divRef} style={{ height: '600px', ...style }} className={className} />;
}) as React.ForwardRefExoticComponent<TinyflowOptions & React.RefAttributes<TinyflowHandle>>;

export default Tinyflow;

// packages/svelte/src/Tinyflow.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import {
        Tinyflow as TinyflowNative,
        type TinyflowOptions
    } from '@tinyflow-ai/ui';
    import '@tinyflow-ai/ui/dist/index.css';

    const { style, className, ...rest }: {
        style?: Record<string, string> | string;
        className?: string;
        // data: TinyflowOptions['data']
    } & Omit<TinyflowOptions, 'element'> = $props();


    // Internal state
    let divRef: HTMLElement | null = null;
    let tinyflowInstance: TinyflowNative | null = null;

    // Expose imperative handle
    export function getData() {
        if (tinyflowInstance) {
            return tinyflowInstance.getData();
        }
        console.warn('Tinyflow instance is not initialized');
        return null;
    }

    export function getInstance() {
        return tinyflowInstance;
    }

    // Lifecycle: Mount
    onMount(() => {
        if (divRef) {
            tinyflowInstance = new TinyflowNative({
                ...rest,
                element: divRef
            });

            return () => {
                if (tinyflowInstance) {
                    tinyflowInstance.destroy();
                    tinyflowInstance = null;
                }
            };
        }
    });
    const defaultStyle = { height: '600px' };
    const combinedStyle = { ...defaultStyle, ...style as Record<string, string> };

    function styleObjectToString(styleObj: Record<string, string>): string {
        return Object.entries(styleObj)
            .map(([key, value]) => `${key}: ${value};`)
            .join(' ');
    }

    const combinedStyleString = typeof style === 'string' ? style : styleObjectToString(combinedStyle);
</script>

<div
    bind:this={divRef}
    style={combinedStyleString }
    class={className}
    {...rest}
></div>
