// packages/vue/src/Tinyflow.vue
<template>
    <div ref="divRef" :class="['tinyflow', className]" :style="style" />
</template>

<script setup lang="ts">
import { Tinyflow as TinyflowNative, TinyflowOptions } from '@tinyflow-ai/ui';
import '@tinyflow-ai/ui/dist/index.css';
import { onMounted, onUnmounted, ref } from 'vue';

const props = defineProps<
    {
        className?: string;
        style?: Record<string, string>;
    } & Omit<TinyflowOptions, 'element'>
>();

const divRef = ref<HTMLDivElement | null>(null);
let tinyflow: TinyflowNative | null = null;

// 安全深拷贝工具函数
function safeDeepClone<T>(obj: T): T {
    if (obj === null || typeof obj !== 'object') return obj;

    try {
        return structuredClone(obj);
    } catch {
        try {
            return JSON.parse(JSON.stringify(obj));
        } catch {
            console.warn('Failed to clone object, returning original (may cause issues)', obj);
            return obj;
        }
    }
}

onMounted(() => {
    if (divRef.value) {
        // 净化 props.data，避免响应式对象或函数污染
        const cleanedProps = { ...props } as any;
        if ('data' in cleanedProps && cleanedProps.data != null) {
            cleanedProps.data = safeDeepClone(cleanedProps.data);
        }

        tinyflow = new TinyflowNative({
            ...cleanedProps,
            element: divRef.value
        });
    }
});

onUnmounted(() => {
    if (tinyflow) {
        tinyflow.destroy();
        tinyflow = null;
    }
});

const getData = () => {
    if (tinyflow) {
        return tinyflow.getData();
    }
    console.warn('Tinyflow instance is not initialized');
    return null;
};

const getInstance = () => {
    if (tinyflow) {
        return tinyflow;
    }
    console.warn('Tinyflow instance is not initialized');
    return null;
};

defineExpose({
    getData,
    getInstance
});
</script>

// packages/react/src/Tinyflow.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import {
    Tinyflow as TinyflowNative,
    type TinyflowOptions as TinyflowNativeOptions
} from '@tinyflow-ai/ui';
import '@tinyflow-ai/ui/dist/index.css';

export type TinyflowOptions = {
    style?: React.CSSProperties;
    className?: string;
} & Omit<TinyflowNativeOptions, 'element'>;

export interface TinyflowHandle {
    getData: () => any;
}

const Tinyflow = forwardRef<TinyflowHandle, TinyflowOptions>((options, ref) => {
    const divRef = useRef<HTMLDivElement | null>(null);
    const tinyflowInstance = useRef<TinyflowNative | null>(null);

    useImperativeHandle(ref, () => ({
        getData: () => {
            if (tinyflowInstance.current) {
                return tinyflowInstance.current.getData();
            }
            console.warn('Tinyflow instance is not initialized');
            return null;
        },
        getInstance: () => {
            if (tinyflowInstance.current) {
                return tinyflowInstance.current;
            }
            console.warn('Tinyflow instance is not initialized');
            return null;
        }
    }));

    const { data, style, className } = options;

    useEffect(() => {
        if (divRef.current) {
            const tinyflow = new TinyflowNative({
                ...options,
                element: divRef.current
                // data: data
            });

            tinyflowInstance.current = tinyflow;

            return () => {
                tinyflow.destroy();
                tinyflowInstance.current = null;
            };
        }
    }, [data]);

    return <div ref={divRef} style={{ height: '600px', ...style }} className={className} />;
}) as React.ForwardRefExoticComponent<TinyflowOptions & React.RefAttributes<TinyflowHandle>>;

export default Tinyflow;
